timeout 1
default postmarketOS
menu title boot prev kernel

label postmarketOS
	kernel /vmlinuz
	fdtdir /
	initrd /initramfs
	append quiet loglevel=2  pmos_boot_uuid=fc55a496-dbb8-4e08-a2ce-369102ed4f15 pmos_root_uuid=a5513363-8a7f-4b04-9df4-50fc6d89a172 pmos_rootfsopts=defaults
